### ISSUE TITLE
[feat]: The Bridge for Youth (Resource suggestion)

### ISSUE THREAD

**Issue by andy5995** [weareinreach/InReach#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Feature Request

This seems like it might be a suitable resource to add:

[The Bridge For Youth](https://bridgeforyouth.org)
>The Bridge for Youth centers youth voice, justice, and equity in all we do, and empowers youth experiencing homelessness through safe shelter, basic needs, and healthy relationships.

[Just For Youth](https://bridgeforyouth.org/youth-faq/)

>LGBTQ+ and looking for a support group? So What if I Am? is a weekly support group for gay, lesbian, bi-sexual, transgender and questioning teens in Mpls. Meets Tues. at The Bridge for Youth. [Learn more about weekly support groups.](https://bridgeforyouth.org/programs/outreach-and-support/)

### If the feature request is approved, would you be willing to submit a PR?

Yes

**Comment by JoeKarow** [comment]
Hi Andy,

Thank you for the suggested resources. I've forwarded them on to our resource coordinators for verification.
