### ISSUE TITLE
[Bug]: Error when displaying impact page

### ISSUE THREAD

**Issue by andy5995** [weareinreach/InReach#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On the [Impact](https://inreach.org/our-impact/) page:

![image](https://user-images.githubusercontent.com/16764864/206105770-68d95d32-1104-422f-8890-31814b32de42.png)

### Version

Live production version

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JoeKarow** [comment]
Thanks, Andy! I've forwarded this over to our WordPress team to handle.

**Comment by JoeKarow** [comment]
Issue has been resolved in WordPress.
